base_dir: data/model
log_level: INFO
data:
  batch_size: 4
  dataset_dir: /home/ps/hongwei/private/data_merge/11_sz_data_merge_output_1909016/
  graph_pkl_filename: /home/ps/hongwei/private/data_merge/12_sensor_graph/adj_mat_hw_directed.pkl
  test_batch_size: 4
  
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 24
  input_dim: 14
  l1_decay: 0
  max_diffusion_step: 1
  num_nodes: 1378
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 256
  seq_len: 24
  use_curriculum_learning: true
  
train:
  base_lr: 0.01
  dropout: 0
  epoch: 64
  epochs: 100
  epsilon: 0.001
  global_step: 3955
  log_dir: data/model
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06

  model_filename: data/model/dcrnn_DR_1_h_24_256-256_lr_0.01_bs_4_0925003108/models-1.0807-3955  


  optimizer: adam
  patience: 50
  steps:
  - 20
  - 30
  - 40
  - 50
  test_every_n_epochs: 10
